### ISSUE TITLE
New Script for Quip

### ISSUE THREAD

**Issue by jessebeach** [jcsteh/axSGrease#21]
1. Put a main region around the document.
2. Add a button to the beginning of main that removes/restores contenteditable from elements in the main content. There is an outstanding question as to what it will take to force browsers to update their accessibility tree after doing that. Just removing the attribute is not good enough based on Jesse’s bookmarklet. We could leave the restore function off it refreshing the page restored it.
3. Wrap comments in role=article.
4. Put button role on the elements that expand comments or expand the comments.
5. Put a label on each comment article that says who did what when, e.g., Jesse commented 1 day ago.
6. It would also be really helpful if there were some way we could make the script help with the export process. Resolving that may be quite a bit more tricky. The menu elements have the right roles, but they don’t reliably respond to screen reader click events and never get DOM focus.

**Comment by plinehan** [comment]
Hey @jessebeach!

Quip has made a bunch of accessibility improvements since you created this issue, and I think most of your requests are now in the product itself!

We have reasonable roles for the vast majority of the document and chat UI, you can disable `contenteditable` with the Ctrl+Alt+Z (Cmd+Opt+Z on Mac) keyboard shortcut, icon-only buttons are now properly `aria-label`led, and menus are keyboard navigable for allowing easy export.

Our accessibility support article has more details: https://www.quipsupport.com/hc/en-us/articles/360016095371-Quip-Accessibility-

We're still actively working on improving accessibility, so this is just the start!

**Comment by jessebeach** [comment]
@plinehan Agree, the work you and your teammates have done is commendable. I agree that this script is no longer necessary. Thank you!
